# Setup
title:               Sascha Baranji
tagline:             'Student der Wirtschaftsinformatik'
description:         '</a>Sascha Baranji</a>.'               
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sascha Baranji
  url:               sascha-baranji.tk
  email:             sascha.baranji@outlook.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

collections:
  algorithmik:
    permalink: /_algorithmik
  datenbanken:
    permalink: /_datenbanken
  programmierung:
    permalink: /_programmierung
